### ISSUE TITLE
sessions + cache possible issue in one connection

### ISSUE THREAD

**Issue by dakorpar** [contributte/redis#14]
I'm looking into code and thinking what to do when U're using redis for both sessions and cache...
What happens if you're on one connection and clear cache?
From what i see all sessions will be lost as well, since flushAll is being called
currently I did this:
```yaml
    connection:
        default:
            uri: tcp://127.0.0.1:6379
            sessions: false
            storage: true
            options: ['parameters': ['database': 1]
        session:
            uri: tcp://127.0.0.1:6379
            sessions: true
            storage: false
            options: ['parameters': ['database': 2]]
```
and this works fine, but there's nothing in README that would explain this, so just wondering should we add this to docs,
or actually also add some checks and not even allow such config, or to automatically force someone to choose db?
